# Change these first
owner: PacViewer # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Pacviewer
    url: https://pacviewer.com
  - name: Pacviewer Phoenix
    url: https://phoenix.pacviewer.com
  - name: Pacviewer Beta
    url: https://beta.pacviewer.com
  - name: Pacviewer API
    url: https://api.pacviewer.com
  - name: Pacviewer Beta API
    url: https://beta-api.pacviewer.com

status-website:
  cname: status.pacviewer.com
  logoUrl: https://raw.githubusercontent.com/PacViewer/uptime/refs/heads/master/static/img/logo.svg
  name: Pacviewer Status
  introTitle: "**Pacviewer** status to check website and api service status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
